<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Еьцептионс\**" />
    <EmbeddedResource Remove="Еьцептионс\**" />
    <None Remove="Еьцептионс\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelBooking.Infrastructure\HotelBooking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
